version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    restart: always #Ensure that the container restarts automatically if it stops.


# bind volumes
version: '3'
services:
  nginx1:
    image: nginx
    ports:
      - "8081:80"
    restart: always
    networks:
      hulk:
        ipv4_address: 192.168.0.4
    volumes:
    #  Bind mount
      - ./html:/usr/share/nginx/html
  nginx2:
    image: nginx
    ports:
      - "8082:80"
    restart: always
    networks:
      hulk:
        ipv4_address: 192.168.0.5
    volumes:    
      # Named Volumes  
      - Nginx_Vol:/usr/share/nginx/html
networks:
  hulk:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/26

volumes:
  Nginx_Vol:



# word press docker compose
# ------------------------

version: '3'
services:
    wordpress_front:
        image: wordpress
        ports:
            - "8089:80"
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_NAME: wordpress_mysql
            WORDPRESS_DB_PASSWORD: "admin_1234"
        networks:
          mysql_nt:
            ipv4_address: "10.0.0.55"
    mysql:
      image: "mysql:5.7"
      environment:
        MYSQL_DATABASE: wordpress_mysql
        MYSQL_ROOT_PASSWORD: "admin_1234"
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        mysql_nt:
            ipv4_address: "10.0.0.45"
networks:
    mysql_nt:
        ipam:
          driver: default
          config:
             - subnet: "10.0.0.0/24"

      

jMFd*5VCE9^VfDpdYK